"""initial_schema

Revision ID: 78e8d802ab2c
Revises:
Create Date: 2026-02-11 15:52:15.758501
"""

from typing import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78e8d802ab2c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), server_default='0', nullable=False),
    sa.Column('metric_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('dimension_value', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ds_date_metric', 'daily_stats', ['stat_date', 'metric_type'], unique=False)
    op.create_index('idx_ds_dimension', 'daily_stats', ['dimension', 'dimension_value'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=20), nullable=False),
    sa.Column('kb_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_institution_type', 'knowledge_bases', ['institution', 'kb_type'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_institution'), 'knowledge_bases', ['institution'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_kb_type'), 'knowledge_bases', ['kb_type'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('procurement_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_opp_source_external_id')
    )
    op.create_index('idx_opp_deadline', 'opportunities', ['deadline'], unique=False)
    op.create_index('idx_opp_source_published', 'opportunities', ['source', 'published_at'], unique=False)
    op.create_index('idx_opp_source_status', 'opportunities', ['source', 'status'], unique=False)
    op.create_index(op.f('ix_opportunities_country'), 'opportunities', ['country'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_external_id'), 'opportunities', ['external_id'], unique=False)
    op.create_index(op.f('ix_opportunities_project_number'), 'opportunities', ['project_number'], unique=False)
    op.create_index(op.f('ix_opportunities_published_at'), 'opportunities', ['published_at'], unique=False)
    op.create_index(op.f('ix_opportunities_sector'), 'opportunities', ['sector'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_table('recharge_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='CNY', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonus_credits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonus_description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('monthly_credit_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('analysis_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='CNY', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sm_category_name', 'system_metrics', ['category', 'metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('language', sa.String(length=10), server_default='zh', nullable=False),
    sa.Column('credits_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('expert_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('level_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_rate', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=True),
    sa.Column('max_rate', sa.Float(), nullable=True),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('applicable_positions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_institutions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_file_hash'), 'knowledge_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='CNY', nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('gateway_order_no', sa.String(length=128), nullable=True),
    sa.Column('gateway_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_order_no'), 'payment_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_step', sa.String(length=50), server_default='upload', nullable=False),
    sa.Column('workflow_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('institution', sa.String(length=10), server_default='adb', nullable=False),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proj_institution', 'projects', ['institution'], unique=False)
    op.create_index('idx_proj_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_opportunity_id'), 'projects', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ss_user_default', 'saved_searches', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('unit_price_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), server_default='other', nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicable_regions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_sectors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_institutions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_price_items_category'), 'unit_price_items', ['category'], unique=False)
    op.create_index(op.f('ix_unit_price_items_name'), 'unit_price_items', ['name'], unique=False)
    op.create_index(op.f('ix_unit_price_items_organization_id'), 'unit_price_items', ['organization_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credits_used_this_month', sa.Integer(), server_default='0', nullable=False),
    sa.Column('analyses_used_this_month', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bid_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('qualification_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_methodology', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commercial_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submission_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('quality_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_analysis', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('bid_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('processing_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processed_pages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vectorized_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('ai_overview', sa.Text(), nullable=True),
    sa.Column('ai_reading_tips', sa.Text(), nullable=True),
    sa.Column('detected_institution', sa.String(length=20), nullable=True),
    sa.Column('analysis_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bd_project_status', 'bid_documents', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_bid_documents_detected_institution'), 'bid_documents', ['detected_institution'], unique=False)
    op.create_index(op.f('ix_bid_documents_project_id'), 'bid_documents', ['project_id'], unique=False)
    op.create_table('bid_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), server_default='投标计划', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_tasks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('bid_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('commercial_score', sa.Integer(), nullable=True),
    sa.Column('win_probability', sa.Integer(), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitive_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_predictions_project_id'), 'bid_predictions', ['project_id'], unique=False)
    op.create_table('expert_match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requirements_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_experts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('team_composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('matching_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_match_results_project_id'), 'expert_match_results', ['project_id'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('education_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('professional_memberships', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_experience_years', sa.Integer(), nullable=True),
    sa.Column('sector_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adb_project_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wb_project_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_project_value', sa.Float(), nullable=True),
    sa.Column('cv_summary', sa.Text(), nullable=True),
    sa.Column('cv_full_text', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('cv_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('skills_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('internal_rating', sa.Float(), nullable=True),
    sa.Column('availability_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('current_project_id', sa.UUID(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_name'), 'experts', ['name'], unique=False)
    op.create_index(op.f('ix_experts_organization_id'), 'experts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_experts_status'), 'experts', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kc_doc_page', 'knowledge_chunks', ['document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_order_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('project_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('remuneration_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('reimbursable_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('equipment_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('subcontract_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('contingency_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('overhead_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('budget_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimation_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), server_default='application/pdf', nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=20), server_default='other', nullable=False),
    sa.Column('parse_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('ocr_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pd_project_type', 'project_documents', ['project_id', 'doc_type'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_table('bid_document_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bid_document_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('section_number', sa.String(length=20), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('detected_by', sa.String(length=20), server_default='regex', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('reading_guide', sa.Text(), nullable=True),
    sa.Column('analysis_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['bid_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bds_doc_type', 'bid_document_sections', ['bid_document_id', 'section_type'], unique=False)
    op.create_index('idx_bds_page_range', 'bid_document_sections', ['bid_document_id', 'start_page', 'end_page'], unique=False)
    op.create_index(op.f('ix_bid_document_sections_bid_document_id'), 'bid_document_sections', ['bid_document_id'], unique=False)
    op.create_table('bid_plan_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('assignee', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_document', sa.String(length=500), nullable=True),
    sa.Column('reference_page', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['bid_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bpt_plan_sort', 'bid_plan_tasks', ['plan_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_bid_plan_tasks_due_date'), 'bid_plan_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_bid_plan_tasks_plan_id'), 'bid_plan_tasks', ['plan_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('unit_price_item_id', sa.UUID(), nullable=True),
    sa.Column('expert_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['project_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_price_item_id'], ['unit_price_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_budget_id'), 'budget_items', ['budget_id'], unique=False)
    op.create_table('expert_skills',
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expert_id', 'skill_id')
    )
    op.create_table('project_document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_document_chunks_document_id'), 'project_document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_document_chunks_project_id'), 'project_document_chunks', ['project_id'], unique=False)
    op.create_table('team_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('person_months', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_home_based', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='proposed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_assignments_expert_id'), 'team_assignments', ['expert_id'], unique=False)
    op.create_index(op.f('ix_team_assignments_project_id'), 'team_assignments', ['project_id'], unique=False)
    op.create_table('bid_document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bid_document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('clause_reference', sa.String(length=100), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bid_document_id'], ['bid_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['bid_document_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bdc_page', 'bid_document_chunks', ['bid_document_id', 'page_number'], unique=False)
    op.create_index('idx_bdc_project_section', 'bid_document_chunks', ['project_id', 'section_type'], unique=False)
    op.create_index(op.f('ix_bid_document_chunks_bid_document_id'), 'bid_document_chunks', ['bid_document_id'], unique=False)
    op.create_index(op.f('ix_bid_document_chunks_project_id'), 'bid_document_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_bid_document_chunks_section_id'), 'bid_document_chunks', ['section_id'], unique=False)
    op.create_table('translation_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['bid_document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'source_lang', 'target_lang', name='uq_translation_cache_hash_lang')
    )
    op.create_index(op.f('ix_translation_cache_content_hash'), 'translation_cache', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_cache_content_hash'), table_name='translation_cache')
    op.drop_table('translation_cache')
    op.drop_index(op.f('ix_bid_document_chunks_section_id'), table_name='bid_document_chunks')
    op.drop_index(op.f('ix_bid_document_chunks_project_id'), table_name='bid_document_chunks')
    op.drop_index(op.f('ix_bid_document_chunks_bid_document_id'), table_name='bid_document_chunks')
    op.drop_index('idx_bdc_project_section', table_name='bid_document_chunks')
    op.drop_index('idx_bdc_page', table_name='bid_document_chunks')
    op.drop_table('bid_document_chunks')
    op.drop_index(op.f('ix_team_assignments_project_id'), table_name='team_assignments')
    op.drop_index(op.f('ix_team_assignments_expert_id'), table_name='team_assignments')
    op.drop_table('team_assignments')
    op.drop_index(op.f('ix_project_document_chunks_project_id'), table_name='project_document_chunks')
    op.drop_index(op.f('ix_project_document_chunks_document_id'), table_name='project_document_chunks')
    op.drop_table('project_document_chunks')
    op.drop_table('expert_skills')
    op.drop_index(op.f('ix_budget_items_budget_id'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_bid_plan_tasks_plan_id'), table_name='bid_plan_tasks')
    op.drop_index(op.f('ix_bid_plan_tasks_due_date'), table_name='bid_plan_tasks')
    op.drop_index('idx_bpt_plan_sort', table_name='bid_plan_tasks')
    op.drop_table('bid_plan_tasks')
    op.drop_index(op.f('ix_bid_document_sections_bid_document_id'), table_name='bid_document_sections')
    op.drop_index('idx_bds_page_range', table_name='bid_document_sections')
    op.drop_index('idx_bds_doc_type', table_name='bid_document_sections')
    op.drop_table('bid_document_sections')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index('idx_pd_project_type', table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_index('idx_kc_doc_page', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_experts_status'), table_name='experts')
    op.drop_index(op.f('ix_experts_organization_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_name'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_expert_match_results_project_id'), table_name='expert_match_results')
    op.drop_table('expert_match_results')
    op.drop_index(op.f('ix_bid_predictions_project_id'), table_name='bid_predictions')
    op.drop_table('bid_predictions')
    op.drop_table('bid_plans')
    op.drop_index(op.f('ix_bid_documents_project_id'), table_name='bid_documents')
    op.drop_index(op.f('ix_bid_documents_detected_institution'), table_name='bid_documents')
    op.drop_index('idx_bd_project_status', table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_table('bid_analyses')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_unit_price_items_organization_id'), table_name='unit_price_items')
    op.drop_index(op.f('ix_unit_price_items_name'), table_name='unit_price_items')
    op.drop_index(op.f('ix_unit_price_items_category'), table_name='unit_price_items')
    op.drop_table('unit_price_items')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_index('idx_ss_user_default', table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_opportunity_id'), table_name='projects')
    op.drop_index('idx_proj_user_status', table_name='projects')
    op.drop_index('idx_proj_institution', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_order_no'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_file_hash'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_table('expert_rates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index('idx_sm_category_name', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('subscription_plans')
    op.drop_table('skill_tags')
    op.drop_table('recharge_packages')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_sector'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_published_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_project_number'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_external_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_country'), table_name='opportunities')
    op.drop_index('idx_opp_source_status', table_name='opportunities')
    op.drop_index('idx_opp_source_published', table_name='opportunities')
    op.drop_index('idx_opp_deadline', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_knowledge_bases_kb_type'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_institution'), table_name='knowledge_bases')
    op.drop_index('idx_kb_institution_type', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index('idx_ds_dimension', table_name='daily_stats')
    op.drop_index('idx_ds_date_metric', table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
